[app]
# The name of your app as displayed in the menu
name = "Wifi Switcher"

# The submenu where your app should appear.
# One of: "Badge", "Music", "Media", "Apps", "Games"
category = "Apps"

# OPTIONAL: Same as above, for compatibility with older firmware
# versions that can't handle categories introduced afterwards.
# One of: "Badge", "Music", "Apps"
# menu = "Badge"

# OPTIONAL: If your app prefers wifi to be off or on when entering.
# Useful if you want more resources (false) or need wifi (true).
# Remove if you don't want to change wifi state!

# We want to override the wifi so best it's already off
wifi_preference = false

[entry]
# The name of your entry point `Application` class
# class = "WifiSwitcherApp"

[metadata]
# Your nickname.  Must be at most 32 characters!
author = "RichardoC"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "MIT"

# URL to the repository of your app.
url = "https://www.github.com/RichardoC/wifi-switcher"

# Description of your app.  Maximum 140 characters!
description = "Switch between multiple Wifi networks"

# Version number of your app.  If you push a commit where this number is
# increased, we interpret this as a new version being released.
#
# Version number must be an integer!
version = "0.0.1"